version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security

  - package-ecosystem: docker
    directory: /AssistantCore.Repository/Database/Flyway
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - security
