<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AssistantCore.ExternalServices</RootNamespace>
    <AssemblyName>AssistantCore.ExternalServices</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.AI.Projects" Version="2.1.0-beta.4" />
    <PackageReference Include="Azure.AI.Projects.Agents" Version="2.1.0-beta.4" />
    <PackageReference Include="MailKit" Version="4.18.0" />
    <PackageReference Include="Microsoft.Agents.AI.Foundry" Version="1.20.0-preview.260831.1" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AssistantCore.Service.Tests" />
  </ItemGroup>

</Project>
