targetScope = 'resourceGroup'

param location string
param environmentName string
param nameSuffix string
param originHostName string
param privateLinkResourceId string
param customDomainName string
param tags object = {}

var profileName = 'afd-assistant-${environmentName}-${nameSuffix}'
var endpointName = 'assistant-${environmentName}-${nameSuffix}'
var originGroupName = 'spa-bff-origin-group'
var originName = 'spa-bff-origin'
var routeName = 'spa-bff-route'
var customDomainResourceName = replace(customDomainName, '.', '-')
var wafPolicyName = 'waf-assistant-${environmentName}-${nameSuffix}'

resource profile 'Microsoft.Cdn/profiles@2025-04-15' = {
  name: profileName
  location: 'global'
  tags: tags
  sku: {
    name: 'Premium_AzureFrontDoor'
  }
  properties: {
    originResponseTimeoutSeconds: 120
  }
}

resource endpoint 'Microsoft.Cdn/profiles/afdEndpoints@2025-04-15' = {
  parent: profile
  name: endpointName
  location: 'global'
  tags: tags
  properties: {
    enabledState: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'ResourceGroupReuse'
  }
}

resource originGroup 'Microsoft.Cdn/profiles/originGroups@2025-04-15' = {
  parent: profile
  name: originGroupName
  properties: {
    healthProbeSettings: {
      probeIntervalInSeconds: 60
      probePath: '/health/live'
      probeProtocol: 'Https'
      probeRequestType: 'GET'
    }
    loadBalancingSettings: {
      additionalLatencyInMilliseconds: 50
      sampleSize: 4
      successfulSamplesRequired: 3
    }
    sessionAffinityState: 'Disabled'
  }
}

resource origin 'Microsoft.Cdn/profiles/originGroups/origins@2025-04-15' = {
  parent: originGroup
  name: originName
  properties: {
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
    hostName: originHostName
    httpPort: 80
    httpsPort: 443
    originHostHeader: originHostName
    priority: 1
    weight: 1000
    sharedPrivateLinkResource: {
      groupId: 'managedEnvironments'
      privateLink: {
        id: privateLinkResourceId
      }
      privateLinkLocation: location
      requestMessage: 'OnPremia Front Door private origin'
      status: 'Pending'
    }
  }
}

resource customDomain 'Microsoft.Cdn/profiles/customDomains@2025-04-15' = {
  parent: profile
  name: customDomainResourceName
  properties: {
    hostName: customDomainName
    tlsSettings: {
      certificateType: 'ManagedCertificate'
      minimumTlsVersion: 'TLS12'
      cipherSuiteSetType: 'TLS12_2023'
    }
  }
}

resource route 'Microsoft.Cdn/profiles/afdEndpoints/routes@2025-04-15' = {
  parent: endpoint
  name: routeName
  properties: {
    customDomains: [
      {
        id: customDomain.id
      }
    ]
    enabledState: 'Enabled'
    forwardingProtocol: 'HttpsOnly'
    httpsRedirect: 'Enabled'
    linkToDefaultDomain: 'Disabled'
    originGroup: {
      id: originGroup.id
    }
    patternsToMatch: [
      '/*'
    ]
    supportedProtocols: [
      'Http'
      'Https'
    ]
  }
  dependsOn: [origin]
}

resource wafPolicy 'Microsoft.Network/FrontDoorWebApplicationFirewallPolicies@2025-03-01' = {
  name: wafPolicyName
  location: 'Global'
  tags: tags
  sku: {
    name: 'Premium_AzureFrontDoor'
  }
  properties: {
    policySettings: {
      enabledState: 'Enabled'
      mode: 'Prevention'
      requestBodyCheck: 'Enabled'
    }
    customRules: {
      rules: [
        {
          name: 'GraphWebhookRateLimit'
          priority: 10
          ruleType: 'RateLimitRule'
          rateLimitDurationInMinutes: 1
          rateLimitThreshold: 300
          action: 'Block'
          enabledState: 'Enabled'
          groupBy: [
            {
              variableName: 'SocketAddr'
            }
          ]
          matchConditions: [
            {
              matchVariable: 'RequestUri'
              operator: 'Contains'
              matchValue: [
                '/webhooks/microsoft-graph'
              ]
              negateCondition: false
            }
          ]
        }
        {
          name: 'BffLoginRateLimit'
          priority: 20
          ruleType: 'RateLimitRule'
          rateLimitDurationInMinutes: 1
          rateLimitThreshold: 30
          action: 'Block'
          enabledState: 'Enabled'
          groupBy: [
            {
              variableName: 'SocketAddr'
            }
          ]
          matchConditions: [
            {
              matchVariable: 'RequestUri'
              operator: 'Contains'
              matchValue: [
                '/bff/login'
              ]
              negateCondition: false
            }
          ]
        }
      ]
    }
    managedRules: {
      managedRuleSets: [
        {
          ruleSetType: 'DefaultRuleSet'
          ruleSetVersion: '2.1'
        }
        {
          ruleSetType: 'Microsoft_BotManagerRuleSet'
          ruleSetVersion: '1.0'
        }
      ]
    }
  }
}

resource securityPolicy 'Microsoft.Cdn/profiles/securityPolicies@2025-04-15' = {
  parent: profile
  name: 'waf-security-policy'
  properties: {
    parameters: {
      type: 'WebApplicationFirewall'
      wafPolicy: {
        id: wafPolicy.id
      }
      associations: [
        {
          domains: [
            {
              id: customDomain.id
            }
          ]
          patternsToMatch: [
            '/*'
          ]
        }
      ]
    }
  }
}

output profileName string = profile.name
output endpointName string = endpoint.name
output endpointHostName string = endpoint.properties.hostName
output customDomainId string = customDomain.id
output originId string = origin.id
output wafPolicyId string = wafPolicy.id
