<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AssistantCore.Service</RootNamespace>
    <AssemblyName>AssistantCore.Service</AssemblyName>
    <UserSecretsId>54151ca2-3e47-4ec9-bbdb-484b93dd3a6c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Blobs" Version="1.5.4" />
    <PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Keys" Version="1.6.4" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.13.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssistantCore.ExternalServices\AssistantCore.ExternalServices.csproj" />
    <ProjectReference Include="..\AssistantCore.Repository\AssistantCore.Repository.csproj" />
  </ItemGroup>

</Project>
